# cryptocurrency market data
https://api.coingecko.com/api/v3/coins/markets
# python packages
pip install requests pandas openpyxl

# importing libraries
import requests
import pandas as pd
import openpyxl

In [1]:
import requests 
import pandas as pd
import openpyxl
import time
from openpyxl import Workbook
import schedule
import logging

In [3]:
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
## Step1 fetching data 
def fetch_crypto_data():    
    url="https://api.coingecko.com/api/v3/coins/markets"
    params={
        "vs_currency":'Usd',
        "order":'market_cap',
        'per_page':50,
        'page':1,
        'sparkline':'false'
    }
    response=requests.get(url,params=params,timeout=15)
    data=response.json()
    if data :
        logging.info('Fetching data successfully..!')
    else:
        logging.warning('Error Fetching data..! Api data Is Empty ')

    return data
crypto_data=fetch_crypto_data()
def process_crypto_data(crypto_data):
    if crypto_data is None:
        logging.warning("No data to process.")
        return None

crypto_list=[]
for coin in crypto_data:
    crypto_list.append([
        coin['name'],
        coin['symbol'].upper(),
        coin['current_price'],
        coin['market_cap'],
        coin['total_volume'],
        coin['price_change_percentage_24h']
    ])

2025-02-12 15:58:10,948 - INFO - Fetching data successfully..!

In [4]:
#df=fetch_crypto_data()
df=pd.DataFrame(crypto_list,columns=["Name", "Symbol", "Price (USD)", "Market Cap", "24h Volume", "24h Price Change (%)"])
print(df)

                 Name  Symbol   Price (USD)     Market Cap   24h Volume  \
0             Bitcoin     BTC  96040.000000  1905528543545  37004476886
1            Ethereum     ETH   2622.960000   316520236861  20090029671
2              Tether    USDT      0.999961   141947045747  65915034582
3                 XRP     XRP      2.410000   139424103400   3909686600
4              Solana     SOL    196.110000    95831357628   3516735344
5                 BNB     BNB    648.730000    94475598783   1268906057
6                USDC    USDC      0.999929    56037834366   7800747057
7            Dogecoin    DOGE      0.254139    37656577622   1345677793
8             Cardano     ADA      0.785160    28184134588   1283168234
9   Lido Staked Ether   STETH   2620.830000    24787083612    112815683
10               TRON     TRX      0.242214    20877090527    717034894
11    Wrapped Bitcoin    WBTC  96018.000000    12397413295    417302839
12          Chainlink    LINK     18.510000    11824008501    507559101
13      Wrapped stETH  WSTETH   3129.370000    10528997210     77544605
14          Avalanche    AVAX     25.060000    10332860503    336337501
15                Sui     SUI      3.270000    10125241579   1310571238
16            Stellar     XLM      0.316709     9701946111    319283143
17          Shiba Inu    SHIB      0.000016     9321311612    228997208
18            Toncoin     TON      3.730000     9305018196    140794871
19          LEO Token     LEO      9.840000     9100260088       492683
20           Litecoin     LTC    116.780000     8834554264   1372236081
21             Hedera    HBAR      0.223389     8552434426    257141099
22               USDS    USDS      0.998960     8438578753      7623517
23        Hyperliquid    HYPE     23.660000     7903919623    115169083
24               WETH    WETH   2622.750000     7686360550    777037715
25           Polkadot     DOT      4.880000     7436156269    225571055
26       Bitget Token     BGB      6.190000     7429794947    291440230
27       Bitcoin Cash     BCH    329.790000     6547159214    143857238
28        Ethena USDe    USDE      0.998533     6009485998     99257995
29             MANTRA      OM      5.880000     5717764982    306512675
30            Uniswap     UNI      9.400000     5651815389    303446810
31       Wrapped eETH   WEETH   2779.210000     5298021728      7996521
32               Ondo    ONDO      1.340000     4247808255    388304695
33             Monero     XMR    221.920000     4098640394     55163019
34               Pepe    PEPE      0.000010     4042454034    868069357
35      WhiteBIT Coin     WBT     27.400000     3950439357     19335000
36      NEAR Protocol    NEAR      3.180000     3775323108    223221739
37               Aave    AAVE    243.390000     3672566979    268754620
38                Dai     DAI      1.000000     3475379207    219974394
39              Aptos     APT      5.950000     3422025012    228055130
40             Mantle     MNT      1.013000     3410781348    117633452
41  Internet Computer     ICP      7.080000     3402030123     98763231
42          Bittensor     TAO    400.190000     3290255372    197489663
43              sUSDS   SUSDS      1.032000     3246849474       238900
44   Ethereum Classic     ETC     20.440000     3085357980    103736587
45     Official Trump   TRUMP     15.230000     3045696980    774029655
46                OKB     OKB     50.160000     3008404113      9907828
47               Gate      GT     22.120000     2784518399     14226278
48            VeChain     VET      0.033187     2690850449     50306656
49     POL (ex-MATIC)     POL      0.308224     2642233258     85719356

    24h Price Change (%)
0               -2.12901
1               -2.98165
2               -0.01850
3               -3.25935
4               -3.16355
5                1.26251
6                0.00180
7               -4.32252
8               -1.80317
9               -3.03929
10              -1.34400
11              -2.02513
12              -4.85478
13              -3.29347
14              -5.87987
15              -7.79396
16              -4.93268
17              -2.72662
18              -3.56361
19              -0.49178
20              -8.42517
21              -7.33428
22              -0.06624
23              -4.17065
24              -3.01786
25              -3.50977
26              -3.64430
27              -2.71422
28              -0.24554
29              -1.51095
30              -5.36417
31              -3.07970
32              -3.17879
33              -1.61351
34              -7.45775
35              -1.95394
36              -5.22575
37              -5.98306
38               0.02627
39              -4.12821
40              -3.62165
41              -3.55287
42              -6.65895
43              -0.43542
44              -3.40151
45              -6.10022
46               0.57478
47              -1.04496
48              -4.93901
49              -4.49874

In [5]:
# savaing data to excel
def save_to_excel(df,filename='Crypto_data.xlsx'):
    try:
        if df is not None:
            df.to_excel(filename,index=False)
            print('Data is successfully saved to file..!')
        else:
            print('Data is not saved.!!')
            return None
    except Exception as e:
        print('Error may occuring while saving file.Please check once again ..!!',e)
        return None
    return df

df1=save_to_excel(df)
print(df1)

Data is successfully saved to file..!
                 Name  Symbol   Price (USD)     Market Cap   24h Volume  \
0             Bitcoin     BTC  96040.000000  1905528543545  37004476886
1            Ethereum     ETH   2622.960000   316520236861  20090029671
2              Tether    USDT      0.999961   141947045747  65915034582
3                 XRP     XRP      2.410000   139424103400   3909686600
4              Solana     SOL    196.110000    95831357628   3516735344
5                 BNB     BNB    648.730000    94475598783   1268906057
6                USDC    USDC      0.999929    56037834366   7800747057
7            Dogecoin    DOGE      0.254139    37656577622   1345677793
8             Cardano     ADA      0.785160    28184134588   1283168234
9   Lido Staked Ether   STETH   2620.830000    24787083612    112815683
10               TRON     TRX      0.242214    20877090527    717034894
11    Wrapped Bitcoin    WBTC  96018.000000    12397413295    417302839
12          Chainlink    LINK     18.510000    11824008501    507559101
13      Wrapped stETH  WSTETH   3129.370000    10528997210     77544605
14          Avalanche    AVAX     25.060000    10332860503    336337501
15                Sui     SUI      3.270000    10125241579   1310571238
16            Stellar     XLM      0.316709     9701946111    319283143
17          Shiba Inu    SHIB      0.000016     9321311612    228997208
18            Toncoin     TON      3.730000     9305018196    140794871
19          LEO Token     LEO      9.840000     9100260088       492683
20           Litecoin     LTC    116.780000     8834554264   1372236081
21             Hedera    HBAR      0.223389     8552434426    257141099
22               USDS    USDS      0.998960     8438578753      7623517
23        Hyperliquid    HYPE     23.660000     7903919623    115169083
24               WETH    WETH   2622.750000     7686360550    777037715
25           Polkadot     DOT      4.880000     7436156269    225571055
26       Bitget Token     BGB      6.190000     7429794947    291440230
27       Bitcoin Cash     BCH    329.790000     6547159214    143857238
28        Ethena USDe    USDE      0.998533     6009485998     99257995
29             MANTRA      OM      5.880000     5717764982    306512675
30            Uniswap     UNI      9.400000     5651815389    303446810
31       Wrapped eETH   WEETH   2779.210000     5298021728      7996521
32               Ondo    ONDO      1.340000     4247808255    388304695
33             Monero     XMR    221.920000     4098640394     55163019
34               Pepe    PEPE      0.000010     4042454034    868069357
35      WhiteBIT Coin     WBT     27.400000     3950439357     19335000
36      NEAR Protocol    NEAR      3.180000     3775323108    223221739
37               Aave    AAVE    243.390000     3672566979    268754620
38                Dai     DAI      1.000000     3475379207    219974394
39              Aptos     APT      5.950000     3422025012    228055130
40             Mantle     MNT      1.013000     3410781348    117633452
41  Internet Computer     ICP      7.080000     3402030123     98763231
42          Bittensor     TAO    400.190000     3290255372    197489663
43              sUSDS   SUSDS      1.032000     3246849474       238900
44   Ethereum Classic     ETC     20.440000     3085357980    103736587
45     Official Trump   TRUMP     15.230000     3045696980    774029655
46                OKB     OKB     50.160000     3008404113      9907828
47               Gate      GT     22.120000     2784518399     14226278
48            VeChain     VET      0.033187     2690850449     50306656
49     POL (ex-MATIC)     POL      0.308224     2642233258     85719356

    24h Price Change (%)
0               -2.12901
1               -2.98165
2               -0.01850
3               -3.25935
4               -3.16355
5                1.26251
6                0.00180
7               -4.32252
8               -1.80317
9               -3.03929
10              -1.34400
11              -2.02513
12              -4.85478
13              -3.29347
14              -5.87987
15              -7.79396
16              -4.93268
17              -2.72662
18              -3.56361
19              -0.49178
20              -8.42517
21              -7.33428
22              -0.06624
23              -4.17065
24              -3.01786
25              -3.50977
26              -3.64430
27              -2.71422
28              -0.24554
29              -1.51095
30              -5.36417
31              -3.07970
32              -3.17879
33              -1.61351
34              -7.45775
35              -1.95394
36              -5.22575
37              -5.98306
38               0.02627
39              -4.12821
40              -3.62165
41              -3.55287
42              -6.65895
43              -0.43542
44              -3.40151
45              -6.10022
46               0.57478
47              -1.04496
48              -4.93901
49              -4.49874

In [6]:
df1.head(5)

,Name,Symbol,Price (USD),Market Cap,24h Volume,24h Price Change (%)
0,Bitcoin,BTC,96040.000000,1905528543545,37004476886,-2.12901
1,Ethereum,ETH,2622.960000,316520236861,20090029671,-2.98165
2,Tether,USDT,0.999961,141947045747,65915034582,-0.01850
3,XRP,XRP,2.410000,139424103400,3909686600,-3.25935
4,Solana,SOL,196.110000,95831357628,3516735344,-3.16355

In [7]:
## Step2:  Data Anylsis
# a.Top 5 Cryptocurrencies by Market Cap
df3=df1.sort_values(by='Market Cap',ascending=False).head(5)
df3

,Name,Symbol,Price (USD),Market Cap,24h Volume,24h Price Change (%)
0,Bitcoin,BTC,96040.000000,1905528543545,37004476886,-2.12901
1,Ethereum,ETH,2622.960000,316520236861,20090029671,-2.98165
2,Tether,USDT,0.999961,141947045747,65915034582,-0.01850
3,XRP,XRP,2.410000,139424103400,3909686600,-3.25935
4,Solana,SOL,196.110000,95831357628,3516735344,-3.16355

In [8]:
# b.Average Price of the Top 50 Cryptocurrencies
avg_price=df['Price (USD)'].mean()
avg_price

4165.299308608601

In [9]:
# c.Highest and Lowest 24-Hour Percentage Price Change
highest=df.loc[df["24h Price Change (%)"].idxmax()]
highest

Name                            BNB
Symbol                          BNB
Price (USD)                  648.73
Market Cap              94475598783
24h Volume               1268906057
24h Price Change (%)        1.26251
Name: 5, dtype: object

In [10]:
Lowest=df.loc[df["24h Price Change (%)"].idxmin()]
Lowest

Name                      Litecoin
Symbol                         LTC
Price (USD)                 116.78
Market Cap              8834554264
24h Volume              1372236081
24h Price Change (%)      -8.42517
Name: 20, dtype: object

In [11]:
def update_crypto_data():
    print(" Fetching live crypto data...")
    crypto_data = fetch_crypto_data()
    df = process_crypto_data(crypto_data)
    save_to_excel(df)

schedule.every(1).minutes.do(update_crypto_data)

print("Live crypto data updates started... ..!")

while True:
    schedule.run_pending()
    time.sleep(1)

Live crypto data updates started... ..!
 Fetching live crypto data...

2025-02-12 16:00:14,342 - INFO - Fetching data successfully..!

Data is not saved.!!

2025-02-12 16:01:14,491 - INFO - Fetching data successfully..!

 Fetching live crypto data...
Data is not saved.!!

2025-02-12 16:02:14,671 - INFO - Fetching data successfully..!

 Fetching live crypto data...
Data is not saved.!!

2025-02-12 16:03:14,830 - INFO - Fetching data successfully..!

 Fetching live crypto data...
Data is not saved.!!

KeyboardInterrupt: